# Generated by Django 6.0.1 on 2026-01-31 01:30

import cloudinary_storage.storage
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Educacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institucion', models.CharField(max_length=150)),
                ('titulo', models.CharField(max_length=150)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Habilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('nivel', models.IntegerField(help_text='Nivel del 1 al 5')),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nnombres', models.CharField(blank=True, max_length=60, null=True)),
                ('apellidos', models.CharField(blank=True, max_length=60, null=True)),
                ('cedula', models.CharField(blank=True, max_length=20, null=True)),
                ('edad', models.IntegerField(blank=True, null=True)),
                ('nacionalidad', models.CharField(blank=True, max_length=60, null=True)),
                ('fecha_de_nacimiento', models.DateField(blank=True, null=True)),
                ('sexo', models.CharField(blank=True, max_length=20, null=True)),
                ('estado_civil', models.CharField(blank=True, max_length=30, null=True)),
                ('discapacidad', models.BooleanField(default=False)),
                ('porcentaje_de_discapacidad', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('profesion', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('perfil_activo', models.IntegerField(default=1)),
                ('lugar_de_nacimiento', models.CharField(blank=True, max_length=60, null=True)),
                ('licencia_de_conducir', models.CharField(blank=True, max_length=6, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=20)),
                ('telefono_convencional', models.CharField(blank=True, max_length=15, null=True)),
                ('ubicacion', models.CharField(max_length=100)),
                ('direccion_de_trabajo', models.CharField(blank=True, max_length=50, null=True)),
                ('direccion_domiciliaria', models.CharField(blank=True, max_length=50, null=True)),
                ('sitio_web', models.URLField(blank=True)),
                ('linkedin', models.URLField(blank=True)),
                ('github', models.URLField(blank=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='perfil/')),
            ],
        ),
        migrations.CreateModel(
            name='Referencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('empresa', models.CharField(max_length=100)),
                ('cargo', models.CharField(max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Experiencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(max_length=150)),
                ('empresa', models.CharField(max_length=150)),
                ('lugar_de_la_empresa', models.CharField(blank=True, max_length=50, null=True)),
                ('email_de_la_empresa', models.EmailField(blank=True, max_length=100, null=True)),
                ('sitio_web_de_la_empresa', models.URLField(blank=True, max_length=100, null=True)),
                ('nombre_del_contacto_empresarial', models.CharField(blank=True, max_length=100, null=True)),
                ('telefono_del_contacto_empresarial', models.CharField(blank=True, max_length=60, null=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('descripcion', models.TextField()),
                ('activar_para_que_se_vea_en_front', models.BooleanField(default=True)),
                ('ruta_del_certificado', models.FileField(blank=True, null=True, upload_to='certificados/experiencia/')),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiencias', to='cv.perfil')),
            ],
            options={
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='CursoRealizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_curso', models.CharField(max_length=200)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('total_horas', models.IntegerField(blank=True, null=True)),
                ('descripcion_curso', models.TextField(blank=True)),
                ('entidad_patrocinadora', models.CharField(blank=True, max_length=150, null=True)),
                ('nombre_contacto_auspicia', models.CharField(blank=True, max_length=120, null=True)),
                ('telefono_contacto_auspicia', models.CharField(blank=True, max_length=40, null=True)),
                ('email_empresa_patrocinadora', models.EmailField(blank=True, max_length=254, null=True)),
                ('activar_para_que_se_vea_enfront', models.BooleanField(default=True)),
                ('ruta_certificado', models.FileField(blank=True, null=True, upload_to='certificados/cursos/')),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cursos_realizados', to='cv.perfil')),
            ],
            options={
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Certificado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('institucion', models.CharField(max_length=200)),
                ('fecha', models.DateField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='certificados/previews/')),
                ('archivo', models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='certificados/pdf/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('drive_file_id', models.CharField(blank=True, help_text='ID del archivo en Google Drive (lo que va entre /d/ y /view)', max_length=200, null=True)),
                ('drive_share_url', models.URLField(blank=True, help_text='Link compartido de Drive (opcional si usas drive_file_id)', null=True)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificados', to='cv.perfil')),
            ],
        ),
        migrations.CreateModel(
            name='ProductoAcademico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_recurso', models.CharField(max_length=200)),
                ('clasificador', models.CharField(blank=True, max_length=120, null=True)),
                ('descripcion', models.TextField(blank=True)),
                ('activar_para_que_se_vea_enfront', models.BooleanField(default=True)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos_academicos', to='cv.perfil')),
            ],
        ),
        migrations.CreateModel(
            name='ProductoLaboral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto', models.CharField(max_length=200)),
                ('fecha_producto', models.DateField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True)),
                ('activar_para_que_se_vea_enfront', models.BooleanField(default=True)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos_laborales', to='cv.perfil')),
            ],
            options={
                'ordering': ['-fecha_producto'],
            },
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('tecnologias', models.CharField(max_length=300)),
                ('github', models.URLField(blank=True, null=True)),
                ('demo', models.URLField(blank=True, null=True)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proyectos', to='cv.perfil')),
            ],
        ),
        migrations.CreateModel(
            name='Reconocimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_reconocimiento', models.CharField(choices=[('Académico', 'Académico'), ('Público', 'Público'), ('Privado', 'Privado')], max_length=20)),
                ('fecha_reconocimiento', models.DateField(blank=True, null=True)),
                ('descripcion_reconocimiento', models.TextField(blank=True)),
                ('entidad_patrocinadora', models.CharField(blank=True, max_length=150, null=True)),
                ('nombre_contacto_auspicia', models.CharField(blank=True, max_length=120, null=True)),
                ('telefono_contacto_auspicia', models.CharField(blank=True, max_length=40, null=True)),
                ('activar_para_que_se_vea_enfront', models.BooleanField(default=True)),
                ('ruta_certificado', models.FileField(blank=True, null=True, upload_to='certificados/reconocimientos/')),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reconocimientos', to='cv.perfil')),
            ],
            options={
                'ordering': ['-fecha_reconocimiento'],
            },
        ),
        migrations.CreateModel(
            name='VentaGarage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_del_producto', models.CharField(max_length=100)),
                ('estado_del_producto', models.CharField(choices=[('Bueno', 'Bueno'), ('Regular', 'Regular')], max_length=40)),
                ('descripcion', models.TextField(blank=True)),
                ('valor_del_bien', models.DecimalField(decimal_places=2, max_digits=8)),
                ('imagen_del_producto', models.ImageField(blank=True, null=True, upload_to='venta_garage/')),
                ('activar_para_que_se_vea_enfront', models.BooleanField(default=True)),
                ('perfil', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ventas_garage', to='cv.perfil')),
            ],
            options={
                'db_table': 'venta_garage',
                'ordering': ['nombre_del_producto'],
            },
        ),
    ]
