# Generated by Django 6.0 on 2026-01-07 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('institucion', models.CharField(max_length=200)),
                ('fecha', models.DateField()),
                ('imagen', models.ImageField(upload_to='certificados/')),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificados', to='cv.perfil')),
            ],
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('tecnologias', models.CharField(max_length=300)),
                ('github', models.URLField(blank=True, null=True)),
                ('demo', models.URLField(blank=True, null=True)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proyectos', to='cv.perfil')),
            ],
        ),
    ]
