# Generated by Django 6.0.1 on 2026-01-31 01:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='educacion',
            name='perfil',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='educaciones', to='cv.perfil'),
            preserve_default=False,
        ),
    ]
