# Generated by Django 6.0.1 on 2026-01-31 01:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0002_educacion_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='habilidad',
            name='perfil',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='habilidades', to='cv.perfil'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='referencia',
            name='perfil',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='referencias', to='cv.perfil'),
            preserve_default=False,
        ),
    ]
