# Generated by Django 6.0.1 on 2026-01-31 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0003_habilidad_perfil_referencia_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='educacion',
            name='activar_para_que_se_vea_en_front',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='habilidad',
            name='activar_para_que_se_vea_en_front',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='referencia',
            name='activar_para_que_se_vea_en_front',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='referencia',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
    ]
