# Generated by Django 6.0.1 on 2026-01-28 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0004_remove_referencia_descripcion_perfil_cedula_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='direcciondomiciliaria',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='direcciontrabajo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='licenciaconducir',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='lugarnacimiento',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='perfilactivo',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='perfil',
            name='sitioweb',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='telefonoconvencional',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
