# Generated by Django 6.0.1 on 2026-01-31 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0004_educacion_activar_para_que_se_vea_en_front_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cursorealizado',
            old_name='activar_para_que_se_vea_enfront',
            new_name='activar_para_que_se_vea_en_front',
        ),
        migrations.RenameField(
            model_name='productoacademico',
            old_name='activar_para_que_se_vea_enfront',
            new_name='activar_para_que_se_vea_en_front',
        ),
        migrations.RenameField(
            model_name='productolaboral',
            old_name='activar_para_que_se_vea_enfront',
            new_name='activar_para_que_se_vea_en_front',
        ),
        migrations.RenameField(
            model_name='reconocimiento',
            old_name='activar_para_que_se_vea_enfront',
            new_name='activar_para_que_se_vea_en_front',
        ),
        migrations.RenameField(
            model_name='ventagarage',
            old_name='activar_para_que_se_vea_enfront',
            new_name='activar_para_que_se_vea_en_front',
        ),
    ]
