# Generated by Django 6.0.1 on 2026-02-02 15:35

import cv.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0005_rename_activar_para_que_se_vea_enfront_cursorealizado_activar_para_que_se_vea_en_front_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificado',
            name='activar_para_que_se_vea_en_front',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='certificado',
            name='fecha',
            field=models.DateField(validators=[cv.models.validar_fecha_no_futura]),
        ),
        migrations.AlterField(
            model_name='cursorealizado',
            name='fecha_fin',
            field=models.DateField(blank=True, null=True, validators=[cv.models.validar_fecha_no_futura]),
        ),
        migrations.AlterField(
            model_name='cursorealizado',
            name='fecha_inicio',
            field=models.DateField(blank=True, null=True, validators=[cv.models.validar_fecha_no_futura]),
        ),
        migrations.AlterField(
            model_name='educacion',
            name='fecha_fin',
            field=models.DateField(blank=True, null=True, validators=[cv.models.validar_fecha_no_futura]),
        ),
        migrations.AlterField(
            model_name='educacion',
            name='fecha_inicio',
            field=models.DateField(validators=[cv.models.validar_fecha_no_futura]),
        ),
        migrations.AlterField(
            model_name='experiencia',
            name='fecha_fin',
            field=models.DateField(blank=True, null=True, validators=[cv.models.validar_fecha_no_futura]),
        ),
        migrations.AlterField(
            model_name='experiencia',
            name='fecha_inicio',
            field=models.DateField(validators=[cv.models.validar_fecha_no_futura]),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='fecha_de_nacimiento',
            field=models.DateField(blank=True, null=True, validators=[cv.models.validar_fecha_no_futura]),
        ),
        migrations.AlterField(
            model_name='productolaboral',
            name='fecha_producto',
            field=models.DateField(blank=True, null=True, validators=[cv.models.validar_fecha_no_futura]),
        ),
        migrations.AlterField(
            model_name='reconocimiento',
            name='fecha_reconocimiento',
            field=models.DateField(blank=True, null=True, validators=[cv.models.validar_fecha_no_futura]),
        ),
        migrations.AlterField(
            model_name='ventagarage',
            name='valor_del_bien',
            field=models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
