# Generated by Django 6.0.1 on 2026-01-28 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0005_perfil_direcciondomiciliaria_perfil_direcciontrabajo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perfil',
            old_name='direcciondomiciliaria',
            new_name='direccion_de_trabajo',
        ),
        migrations.RenameField(
            model_name='perfil',
            old_name='direcciontrabajo',
            new_name='direccion_domiciliaria',
        ),
        migrations.RenameField(
            model_name='perfil',
            old_name='fecha_nacimiento',
            new_name='fecha_de_nacimiento',
        ),
        migrations.RenameField(
            model_name='perfil',
            old_name='licenciaconducir',
            new_name='licencia_de_conducir',
        ),
        migrations.RenameField(
            model_name='perfil',
            old_name='lugarnacimiento',
            new_name='lugar_de_nacimiento',
        ),
        migrations.RenameField(
            model_name='perfil',
            old_name='perfilactivo',
            new_name='perfil_activo',
        ),
        migrations.RenameField(
            model_name='perfil',
            old_name='porcentaje_discapacidad',
            new_name='porcentaje_de_discapacidad',
        ),
        migrations.RenameField(
            model_name='perfil',
            old_name='telefonoconvencional',
            new_name='telefono_convencional',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='sitioweb',
        ),
        migrations.AddField(
            model_name='perfil',
            name='sitio_web',
            field=models.URLField(blank=True),
        ),
    ]
