# Generated by Django 6.0.1 on 2026-01-28 22:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0006_rename_direcciondomiciliaria_perfil_direccion_de_trabajo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExperienciaLaboral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo_desempeñado', models.CharField(max_length=100)),
                ('nombre_de_la_empresa', models.CharField(blank=True, max_length=50, null=True)),
                ('lugar_de_la_empresa', models.CharField(blank=True, max_length=50, null=True)),
                ('email_de_la_empresa', models.EmailField(blank=True, max_length=100, null=True)),
                ('sitio_web_de_la_empresa', models.URLField(blank=True, max_length=100, null=True)),
                ('nombre_del_contacto_empresarial', models.CharField(blank=True, max_length=100, null=True)),
                ('telefono_del_contacto_empresarial', models.CharField(blank=True, max_length=60, null=True)),
                ('fecha_de_inicio_de_gestion', models.DateField()),
                ('fecha_de_fin_de_la_gestion', models.DateField(blank=True, null=True)),
                ('descripcion_de_funciones', models.TextField(max_length=100)),
                ('activar_para_que_se_vea_en_el_front', models.BooleanField(default=True)),
                ('ruta_deñ_certificado', models.FileField(blank=True, null=True, upload_to='certificados/experiencia/')),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiencias', to='cv.perfil')),
            ],
            options={
                'ordering': ['-fecha_de_inicio_de_gestion'],
            },
        ),
    ]
