# Generated by Django 6.0.1 on 2026-01-28 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0007_experiencialaboral'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='experiencia',
            options={'ordering': ['-fecha_inicio']},
        ),
        migrations.AddField(
            model_name='experiencia',
            name='activar_para_que_se_vea_en_front',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='experiencia',
            name='email_de_la_empresa',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='experiencia',
            name='lugar_de_la_empresa',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='experiencia',
            name='nombre_de_la_empresa',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='experiencia',
            name='nombre_del_contacto_empresarial',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='experiencia',
            name='ruta_del_certificado',
            field=models.FileField(blank=True, null=True, upload_to='certificados/experiencia/'),
        ),
        migrations.AddField(
            model_name='experiencia',
            name='sitio_web_de_la_empresa',
            field=models.URLField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='experiencia',
            name='telefono_del_contacto_empresarial',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.DeleteModel(
            name='ExperienciaLaboral',
        ),
    ]
