# Generated by Django 6.0.1 on 2026-01-28 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0008_alter_experiencia_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VentaGarage',
            fields=[
                ('id_venta_garage', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_del_producto', models.CharField(max_length=100)),
                ('estado_del_producto', models.CharField(choices=[('Bueno', 'Bueno'), ('Regular', 'Regular')], max_length=40)),
                ('valor_del_bien', models.DecimalField(decimal_places=2, max_digits=5)),
                ('imagen_del_producto', models.ImageField(blank=True, null=True, upload_to='venta_garage/')),
                ('activar_para_que_se_vea_enfront', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Venta Garage',
                'verbose_name_plural': 'Ventas Garage',
                'db_table': 'venta_garage',
                'ordering': ['nombre_del_producto'],
            },
        ),
    ]
