# Generated by Django 6.0.1 on 2026-01-29 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0009_ventagarage'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='nacionalidad',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
