# Generated by Django 6.0.1 on 2026-01-29 19:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0010_perfil_nacionalidad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificado',
            name='imagen',
        ),
        migrations.AddField(
            model_name='certificado',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='certificados/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'pdf'])]),
        ),
    ]
