# Generated by Django 6.0.1 on 2026-01-29 20:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0011_remove_certificado_imagen_certificado_archivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificado',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='certificados/previews/'),
        ),
        migrations.AlterField(
            model_name='certificado',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='certificados/pdf/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
    ]
